lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='home'),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
]

students/urls.py
from django.urls import path

from .views import create_student
from .views import delete_student
from .views import detail_student
from .views import get_students
from .views import update_student

app_name = 'student'

urlpatterns = [
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('detail/<int:student_id>/', detail_student, name='detail'),
    path('update/<int:student_id>/', update_student, name='update'),
    path('delete/<int:student_id>/', delete_student, name='delete'),
]

students/models.py
from datetime import date

# from students.validators import valid_email_domains
from core.validators import ValidEmailDomain

from dateutil.relativedelta import relativedelta

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models

from faker import Faker


VALID_DOMAINS_LIST = ('@gmail.com', '@yahoo.com', '@test.com')


class Student(models.Model):
    first_name = models.CharField(
        max_length=100,
        verbose_name='first name',
        db_column='first_name',
        validators=[MinLengthValidator(2, '"first_name" field value less than two symbols')]
    )
    last_name = models.CharField(
        max_length=100,
        verbose_name='last name',
        db_column='last_name',
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"last_name" field value less than two symbols'}
    )
    birthday = models.DateField(default=date.today, null=True, blank=True)
    #   email = models.EmailField(validators=[valid_email_domains])
    email = models.EmailField(validators=[ValidEmailDomain(*VALID_DOMAINS_LIST)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_age(self):
        return relativedelta(date.today(), self.birthday).years

    #   class Meta:
    #       db_table = 'student_table'

    @classmethod
    def generate_fake_data(cls, cnt):
        f = Faker()

        for _ in range(cnt):
            first_name = f.first_name()
            last_name = f.last_name()
            email = f'{first_name}.{last_name}{f.random.choice(VALID_DOMAINS_LIST)}'
            birthday = f.date()
            st = cls(first_name=first_name, last_name=last_name, birthday=birthday, email=email)
            try:
                st.full_clean()
                st.save()
            except ValidationError:
                print(f'Incorrect data {first_name}, {last_name}, {email}, {birthday}')

students/forms.py
from django import forms

from .models import Student


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'email',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def clean(self):
        pass

    def clean_birthday(self):
        value = self.cleaned_data.get('birthday')

        return value


class UpdateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

students/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt # noqa

from webargs.djangoparser import use_args
from webargs.fields import Str

from .forms import CreateStudentForm
from .forms import UpdateStudentForm
from .models import Student


@use_args(
    {
        'first_name': Str(required=False),
        'last_name': Str(required=False),
    },
    location='query'
)
def get_students(request, args):
    students = Student.objects.all()

    if len(args) and args.get('first_name') or args.get('last_name'):
        students = students.filter(
            Q(first_name=args.get('first_name', '')) | Q(last_name=args.get('last_name', ''))
        )

    return render(
        request=request,
        template='students/list.html',
        context={
            'title': 'List of students',
            'students': students
        }
    )


def detail_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    return render(request, 'students/details.html', {'student': student})


# @csrf_exempt
def create_student(request):
    if request.method == 'GET':
        form = CreateStudentForm()
    elif request.method == 'POST':
        form = CreateStudentForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'students/create.html', {'form': form})


def update_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.method == 'GET':
        form = UpdateStudentForm(instance=student)
    elif request.method == 'POST':
        form = UpdateStudentForm(request.POST, instance=student)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'students/update.html', {'form': form})


def delete_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.method == 'POST':
        student.delete()
        return HttpResponseRedirect(reverse('list'))

    return render(request, 'students/delete.html', {'student': student})

students/templates/students/create.html
{% extends 'base.html' %}

{% block title %}Create a new student{% endblock %}

{% block content %}
  <form method="get">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input class="btn btn-outline-primary btn-sm" type="submit" value="Create">
    <a class="btn btn-outline-danger btn-sm" href="{% url 'student:list' %}">Cancel</a>
  </form>
{% endblock %}

students/templates/students/delete.html
{% extends 'base.html' %}

{% block title %}Delete student{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove "{{ student.last_name }} {{ student.first_name }}"?</p>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Agree">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'student:list' %}">Cancel</a>
    </form>
{% endblock %}

students/templates/students/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ student.first_name}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <a href="{% url 'student:update' student.pk %}/">{{ student.first_name }} {{ student.last_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ student.email }}</li>
                    <li class="list-group-item">
                        {{ student.birthday }} {% if student.get_age %}
                            <span class="text-muted">({{ student.get_age }} year)</span>
                        {% endif%}
                    </li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{% url 'student:list' %}">Back to list</a>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
{% endblock %}

students/templates/students/list.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}


{% block custom_css %}
    #list {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #list td {
        border: 1px solid #dddd;
        text-align: left;
        padding: 8px;
    }

    #lisr tr:nth-child(even) {
        background-color: #2222;

    }
{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col">
            <form method="get">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingFirstName" placeholder="a" name="first_name" >
                    <label for="floatingFirstName">First name</label>
                </div>
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingLastName" placeholder="b" name="last_name">
                    <label for="floatingLastName">Last name</label>
                </div>
                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
            </form>
        </div>
        <div class="coll-6"></div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>N</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Age</th>
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'student:detail' student.pk %}/">{{ student.first_name }}</a></td>
                        <td>{{ student.last_name }}</td>
                        <td>{% if student.get_age %}{{ student.get_age }}{% endif %}</td>
                        <td><a class="btn btn-outline-primary btn-sm" href="{% url 'student:update' student.pk %}/">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm" href="{% url 'student:delete' student.pk %}/">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

students/templates/students/update.html
{% extends 'base.html' %}

{% block title %}Update student{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Update">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'student:list' %}">Cancel</a>
    </form>
{% endblock %}