groups/urls.py
from django.urls import path

from .views import create_group
from .views import delete_group
from .views import detail_group
from .views import get_groups
from .views import update_group

app_name = 'group'

urlpatterns = [
    path('', get_groups, name='list'),
    path('create/', create_group, name='create'),
    path('detail/<int:group_id>/', detail_group, name='detail'),
    path('update/<int:group_id>/', update_group, name='update'),
    path('delete/<int:group_id>/', delete_group, name='delete'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='home'),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
]

groups/models.py
from datetime import date

from dateutil.relativedelta import relativedelta

from django.core.validators import MinLengthValidator
from django.db import models


class Group(models.Model):
    group_name = models.CharField(
        max_length=100,
        verbose_name='group name',
        db_column='group_name',
        validators=[MinLengthValidator(2, '"group_name" field value less than two symbols')]
    )
    date_start = models.DateField(default=date.today, null=True, blank=True)
    description = models.TextField(
        max_length=300,
        verbose_name='description',
        db_column='description',
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"description" field value less than two symbols'}
    )

    def __str__(self):
        return f'{self.group_name} {self.date_start}\n{self.description}'

    def get_age(self):
        return relativedelta(date.today(), self.date_start).years

groups/forms.py
from django import forms

from .models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'group_name',
            'date_start',
            'description',
        ]

        widgets = {
            'date_start': forms.DateInput(attrs={'type': 'date'})
        }

    def clean(self):
        pass


class UpdateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'group_name',
            'date_start',
            'description',
        ]

        widgets = {
            'date_start': forms.DateInput(attrs={'type': 'date'})
        }

groups/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from webargs.djangoparser import use_args
from webargs.fields import Str

from .forms import CreateGroupForm, UpdateGroupForm
from .models import Group


@use_args(
    {
        'group_name': Str(required=False),
    },
    location='query'
)
def get_groups(request, args):
    groups = Group.objects.all()

    if len(args) and args.get('group_name'):
        groups = groups.filter(
            Q(group_name=args.get('group_name', ''))
        )

    return render(
        request=request,
        template='group/list.html',
        context={
            'title': 'List of groups',
            'groups': groups
        }
    )


def detail_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)

    return render(request, 'groups/details.html', {'group': group})


def create_group(request):
    if request.method == 'GET':
        form = CreateGroupForm()
    elif request.method == 'POST':
        form = CreateGroupForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'groups/create.html', {'form': form})


def update_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)

    if request.method == 'GET':
        form = UpdateGroupForm(instance=group)
    elif request.method == 'POST':
        form = UpdateGroupForm(request.POST, instance=group)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'groups/update.html', {'form': form})


def delete_group(request, student_id):
    group = get_object_or_404(Group, pk=student_id)

    if request.method == 'POST':
        group.delete()
        return HttpResponseRedirect(reverse('list'))

    return render(request, 'groups/delete.html', {'group': group})

groups/templates/groups/create.html
{% extends 'base.html' %}

{% block title %}Create a new group{% endblock %}

{% block content %}
  <form method="get">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input class="btn btn-outline-primary btn-sm" type="submit" value="Create">
    <a class="btn btn-outline-danger btn-sm" href="{% url 'group:list' %}">Cancel</a>
  </form>
{% endblock %}

groups/templates/groups/delete.html
{% extends 'base.html' %}

{% block title %}Delete group{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove "{{ group.group_name }}"?</p>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Agree">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'group:list' %}">Cancel</a>
    </form>
{% endblock %}

groups/templates/groups/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ group.group_name}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <<a href="/groups/update/{{ group.pk }}/">{{ group.group_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ group.date_start }} {% if group.get_age %}
                            <span class="text-muted">({{ group.get_age }} year)</span>
                        {% endif%}
                    </li>
                    <li class="list-group-item">{{ group.description }}</li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{% url 'group:list' %}">Back to list</a>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
{% endblock %}

groups/templates/groups/list.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>N</th>
                    <th>Group name</th>
                    <th>Date start</th>
                    <th>Description</th>
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'group:detail' group.pk %}/">{{ group.group_name }}</a></td>
                        <td>{{ group.date_start }}</td>
                        <td>{{ group.description }}</td>
                        <td><a class="btn btn-outline-primary btn-sm" href="{% url 'group:update' group.pk %}/">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm" href="{% url 'group:delete' group.pk %}/">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

groups/templates/groups/update.html
{% extends 'base.html' %}

{% block title %}Update group{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Update">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'group:list' %}">Cancel</a>
    </form>
{% endblock %}