lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='home'),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
]

teachers/urls.py
from django.urls import path

from .views import create_teacher
from .views import delete_teacher
from .views import detail_teacher
from .views import get_teachers
from .views import update_teacher

app_name = 'teacher'

urlpatterns = [
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('detail/<int:teacher_id>/', detail_teacher, name='detail'),
    path('update/<int:teacher_id>/', update_teacher, name='update'),
    path('delete/<int:teacher_id>/', delete_teacher, name='delete'),
]

teachers/models.py
from datetime import date

from core.validators import ValidEmailDomain

from dateutil.relativedelta import relativedelta

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models

from faker import Faker


VALID_DOMAINS_LIST = ('@gmail.com', '@yahoo.com', '@test.com')


class Teacher(models.Model):
    first_name = models.CharField(
        max_length=100,
        verbose_name='first name',
        db_column='first_name',
        validators=[MinLengthValidator(2, '"first_name" field value less than two symbols')]
    )
    last_name = models.CharField(
        max_length=100,
        verbose_name='last name',
        db_column='last_name',
        validators=[MinLengthValidator(2)],
        error_messages={'min_length': '"last_name" field value less than two symbols'}
    )
    birthday = models.DateField(default=date.today, null=True, blank=True)
    email = models.EmailField(validators=[ValidEmailDomain(*VALID_DOMAINS_LIST)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_age(self):
        return relativedelta(date.today(), self.birthday).years

    #   class Meta:
    #       db_table = 'student_table'

    @classmethod
    def generate_fake_data(cls, cnt):
        f = Faker()

        for _ in range(cnt):
            first_name = f.first_name()
            last_name = f.last_name()
            email = f'{first_name}.{last_name}{f.random.choice(VALID_DOMAINS_LIST)}'
            birthday = f.date()
            st = cls(first_name=first_name, last_name=last_name, birthday=birthday, email=email)
            try:
                st.full_clean()
                st.save()
            except ValidationError:
                print(f'Incorrect data {first_name}, {last_name}, {email}, {birthday}')

teachers/forms.py
from django import forms

from .models import Teacher


class CreateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'email',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def clean(self):
        pass

    def clean_birthday(self):
        value = self.cleaned_data.get('birthday')

        return value


class UpdateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'birthday',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

teachers/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt # noqa

from webargs.djangoparser import use_args
from webargs.fields import Str

from .forms import CreateTeacherForm
from .forms import UpdateTeacherForm
from .models import Teacher


@use_args(
    {
        'first_name': Str(required=False),
        'last_name': Str(required=False),
    },
    location='query'
)
def get_teachers(request, args):
    teachers = Teacher.objects.all()

    if len(args) and args.get('first_name') or args.get('last_name'):
        teachers = teachers.filter(
            Q(first_name=args.get('first_name', '')) | Q(last_name=args.get('last_name', ''))
        )

    return render(
        request=request,
        template='students/list.html',
        context={
            'title': 'List of teachers',
            'teachers': teachers
        }
    )


def detail_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    return render(request, 'teachers/details.html', {'teacher': teacher})


# @csrf_exempt
def create_teacher(request):
    if request.method == 'GET':
        form = CreateTeacherForm()
    elif request.method == 'POST':
        form = CreateTeacherForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'teachers/create.html', {'form': form})


def update_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    if request.method == 'GET':
        form = UpdateTeacherForm(instance=teacher)
    elif request.method == 'POST':
        form = UpdateTeacherForm(request.POST, instance=teacher)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

    return render(request, 'teachers/update.html', {'form': form})


def delete_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('list'))

    return render(request, 'teachers/delete.html', {'teacher': teacher})

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% block title %}Create a new teacher{% endblock %}

{% block content %}
  <form method="get">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input class="btn btn-outline-primary btn-sm" type="submit" value="Create">
    <a class="btn btn-outline-danger btn-sm" href="{% url 'teacher:list' %}">Cancel</a>
  </form>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}Delete teacher{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove "{{ teacher.last_name }} {{ teacher.first_name }}"?</p>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Agree">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'teacher:list' %}">Cancel</a>
    </form>
{% endblock %}

teachers/templates/teachers/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ teacher.first_name}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <a href="{% url 'teacher:update' teacher.pk %}/">{{ teacher.first_name }} {{ teacher.last_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ teacher.email }}</li>
                    <li class="list-group-item">
                        {{ teacher.birthday }} {% if teacher.get_age %}
                            <span class="text-muted">({{ teacher.get_age }} year)</span>
                        {% endif%}
                    </li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{% url 'teacher:list' %}">Back to list</a>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col">
            <form method="get">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingFirstName" placeholder="a" name="first_name" >
                    <label for="floatingFirstName">First name</label>
                </div>
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingLastName" placeholder="b" name="last_name">
                    <label for="floatingLastName">Last name</label>
                </div>
                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
            </form>
        </div>
        <div class="coll-6"></div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>N</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Age</th>
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'teacher:detail' teacher.pk %}/">{{ teacher.first_name }}</a></td>
                        <td>{{ teacher.last_name }}</td>
                        <td>{% if teacher.get_age %}{{ teacher.get_age }}{% endif %}</td>
                        <td><a class="btn btn-outline-primary btn-sm" href="{% url 'teacher:update' teacher.pk %}/">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm" href="{% url 'teacher:delete' teacher.pk %}/">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% block title %}Update teacher{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <input class="btn btn-outline-primary btn-sm" type="submit" value="Update">
        <a class="btn btn-outline-danger btn-sm" href="{% url 'teacher:list' %}">Cancel</a>
    </form>
{% endblock %}