groups/urls.py
from django.urls import path

from .views import create_group
from .views import delete_group
from .views import detail_group
from .views import get_groups
from .views import update_group

app_name = 'group'

urlpatterns = [
    path('', get_groups, name='list'),
    path('create/', create_group, name='create'),
    path('detail/<int:group_id>/', detail_group, name='detail'),
    path('update/<int:group_id>/', update_group, name='update'),
    path('delete/<int:group_id>/', delete_group, name='delete'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='home'),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
]

students/urls.py
from django.urls import path

from .views import create_student
from .views import delete_student
from .views import detail_student
from .views import get_students
from .views import update_student

app_name = 'student'

urlpatterns = [
    path('', get_students, name='list'),
    path('create/', create_student, name='create'),
    path('detail/<int:student_id>/', detail_student, name='detail'),
    path('update/<int:student_id>/', update_student, name='update'),
    path('delete/<int:student_id>/', delete_student, name='delete'),
]

teachers/urls.py
from django.urls import path

from .views import create_teacher
from .views import delete_teacher
from .views import detail_teacher
from .views import get_teachers
from .views import update_teacher

app_name = 'teacher'

urlpatterns = [
    path('', get_teachers, name='list'),
    path('create/', create_teacher, name='create'),
    path('detail/<int:teacher_id>/', detail_teacher, name='detail'),
    path('update/<int:teacher_id>/', update_teacher, name='update'),
    path('delete/<int:teacher_id>/', delete_teacher, name='delete'),
]

templates/includes/navbar.html
{% load static %}

<nav class="navbar stiky-top navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static 'img/logo.jpg' %}" alt="LMS" width="30" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Students
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'student:create' %}">Create</a></li>
            <li><a class="dropdown-item" href="{% url 'student:list' %}">List</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teachers
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'teacher:create' %}">Create</a></li>
            <li><a class="dropdown-item" href="{% url 'teacher:list' %}">List</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'group:create' %}">Create</a></li>
            <li><a class="dropdown-item" href="{% url 'group:list' %}">List</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>